server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /public/storage {
        alias /var/www/storage/app/public;
        try_files $uri $uri/ =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
